services:
  java-helper:
    container_name: java-helper
    image: abhishek1009/java-helper
    build:
      context: .
      dockerfile: Dockerfile.docs
    ports:
      - "8000:8000"
    # volume mount so that it will get the local changes automatically
    volumes:
      - ./:/home/abhishek/workspace/java-helper  # Mounts the local docs directory to /docs in the container
